import type { Metadata } from "next";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/react";


export const metadata: Metadata = {
  title: "Instagram Insight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark bg-slate-900">
        <NextUIProvider>
            {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
